### PR TITLE
Add the Latin Modern Math font for MathML testing.

### PR DESCRIPTION
**Pull request by fred-wang**

### CODE REVIEW

**Comment by mrobinson** [comment]
Does it also make sense to remove the STIX fonts?

**Comment by fred-wang** [comment]
Yes, but not until Latin Modern Math is used for the default font-family on the math element (i.e. can we take https://bugs.webkit.org/show_bug.cgi?id=133604?)

**Comment by mrobinson** [comment]
We can simply wait to update webkitgtk-test-fonts until that is the case. What purpose does it serve to have both in the repository?

**Comment by fred-wang** [comment]
That could help removing the Latin Modern Math woff file from the LayoutTests/ used in the mathml/opentype tests, even if STIX is still used by default. But anyway I'm not really clear about the best way to manage all these changes, so let's wait before taking that.

**Pull request merged**
